logging:
    level:
        org.springframework.data.r2dbc: DEBUG
spring:
    application:
        name: projectBank
    batch:
        initialize-schema: always
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: ${DBPASSWORD:Teste123}
        url: jdbc:sqlserver://${DBSERVER:${CONTAINER_IP:127.0.0.1}}:${DBPORT:1433};database=${DBSERVER_NAME:ProjectBank};trustServerCertificate=true;
        username: ${DBUSER:sa}
    jpa:
        hibernate:
            # CREATE-DROP PARA TESTES, SEMPRE QUE INICIAR ELE VAI FAZER UM CREATE E DROP DA TABELA.
            # UPDATE - Preenche os campos do bd
            #Samuel
            ddl-auto: ${JPA_DDL_AUTO:update}
            database: ${DBSERVER_NAME:ProjectBank}
            show-sql: true
server:
    error:
        include-binding-errors: always
        include-message: always

jwt:
    token-secret: ${JWT_KEY:teste}

    header: Authorization
    secret: my-very-secret-key




